name: rv
channels:
  - pytorch
  - huggingface
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py36h27cfd23_1003
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - cffi=1.14.5=py36h261ae71_0
  - chardet=4.0.0=py36h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - cryptography=3.3.1=py36h3c74f83_1
  - cudatoolkit=10.2.89=hfd86e86_1
  - dataclasses=0.7=py36h06a4308_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - freetype=2.10.4=h5ab3b9f_0
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.2.1=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py36hff7bd54_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1j=h27cfd23_0
  - packaging=20.9=pyhd3eb1b0_0
  - pillow=8.1.0=py36he98fc37_0
  - pip=21.0.1=py36h06a4308_0
  - protobuf=3.14.0=py36h2531618_1
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - python_abi=3.6=1_cp36m
  - pytorch=1.6.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - readline=8.1=h27cfd23_0
  - regex=2020.11.13=py36h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - sacremoses=master=py_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - tokenizers=0.9.4=py36_0
  - torchvision=0.7.0=py36_cu102
  - tqdm=4.56.0=pyhd3eb1b0_0
  - transformers=4.2.2=pyh7b7c402_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - pydantic==1.8
    - scipy==1.5.4
    - tensorboard-logger==0.1.0
    - typing-extensions==3.7.4.3
prefix: /home/zhangpengcheng/miniconda3/envs/rv
